@api = http://localhost:3000/products


GET http://localhost:8000/products
###

POST http://localhost:8000/products
Content-Type: application/json

{
    "pr_name": "Cequr",
    "pr_line":"Simplicity",
    "pr_station":"Harro1",
    "pr_baan":"B987654",
    "pr_units": "ea",
    "created_at":"2023-06-18T22:34:09.000Z",
    "updated_at":"2024-06-18T22:34:09.000Z"
}

###
GET http://localhost:8000/products/5

###
DELETE http://localhost:8000/products/100
###
GET http://localhost:8000/products/count
###
PUT http://localhost:8000/products/1
Content-Type: application/json

{
    "pr_name": "J&J",
    "pr_line":"ElevenSet",
    "pr_station":"Torque",
    "pr_baan":"B987654",
    "pr_units": "ea",
    "created_at":"2023-06-18T22:34:09.000Z",
    "updated_at":"2024-06-18T22:34:09.000Z"
}

###
POST http://localhost:8000/machine_performance
Content-Type: application/json

{
    "id_products": "5",
    "id_stations":"1",
    "created_at":"2024-06-18T22:34:09.000Z",
    "updated_at":"2024-06-18T22:34:09.000Z"
}

### :start_hour, :end_hour, :date and will return de lead_created_at also
GET http://localhost:8000/machine_performance/date_range/11/12/20230927/2

### post machine perfomance with GET
GET http://localhost:8000/machine_performance/post/6/1/2024-06-18T22:34:09.000Z/2024-06-18T22:34:09.000Z

###Get machine performance by Id
GET http://localhost:8000/machine_performance/id/52126

###Get DT reasons by ID
GET http://localhost:8000/downtime_reasons/2

###Send data to update Downtime reason on Machine Performane Table
POST http://localhost:8000/downtime_reasons/update
Content-Type: application/json

{
    "id": "52126",
    "id_dt_reason":"1",
    "dt_reason":"My Downt Time new reason"
}